package com.otterly76.ott.color;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * The members of a colour set, loaded once from {@code assets/ott/color_set_members.csv}
 * (columns: {@code name,scope,block_class,base_block,texture,render,lang}). Drives texture
 * generation, block models, lang and registration so a set is defined in one place.
 *
 * <p>{@code texture} encodes how each member's texture is produced — see the CSV header.
 */
public final class ColorSetMembers {
    private ColorSetMembers() {}

    public static final List<Member> ALL = load();

    public record Member(String name, String scope, String blockClass, String baseBlock,
                         String texture, String render, String lang) {
        public boolean isAllColors() { return "all".equals(scope); }
        public boolean isItem()      { return "(item)".equals(blockClass); }
        /** true when the texture is committed art / reused / unconfirmed (not generated by ColorSetTextureProvider). */
        public boolean isGenerated() {
            return !(texture.equals("art") || texture.startsWith("reuse:") || texture.equals("?"));
        }
    }

    private static List<Member> load() {
        List<Member> list = new ArrayList<>();
        var loader = ColorSetMembers.class.getClassLoader();
        try (var in = loader.getResourceAsStream("assets/ott/color_set_members.csv")) {
            if (in == null) throw new IllegalStateException("assets/ott/color_set_members.csv not found on classpath");
            try (BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = r.readLine()) != null) {
                    String t = line.trim();
                    if (t.isEmpty() || t.startsWith("#") || t.startsWith("name,")) continue;
                    String[] p = line.split(",", 7);
                    if (p.length < 7) continue;
                    list.add(new Member(p[0].trim(), p[1].trim(), p[2].trim(), p[3].trim(),
                            p[4].trim(), p[5].trim(), p[6].trim()));
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("Failed to load color_set_members.csv", e);
        }
        return List.copyOf(list);
    }
}
